FROM --platform=$BUILDPLATFORM elixir:1.13.3-slim

ENV PHOENIX_VERSION=1.6.6

WORKDIR /app

RUN set -ex \
  && apt-get update -y && apt-get upgrade -y \
  && apt-get install -y --no-install-recommends \
    sudo \
    curl \
    git \
    npm \
    build-essential \
    inotify-tools \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN mix do \
  local.hex --force, \
  local.rebar --force, \
  archive.install --force hex phx_new ${PHOENIX_VERSION}

CMD ["mix", "phx.server"]
